### ISSUE TITLE
Mekanism config needs updated

### ISSUE THREAD

**Issue by VortexJD** [ImpactFlux/ImpactFlux-Modpack#86]
mekanism.cfg
D:HydrogenEnergyDensity=2000.0
needs changed to something less.  Current Mekanism default is 200, not 2000.  Was a change Mekanism made back in Aug 14 that never found its way into this pack.

https://github.com/aidancbrady/Mekanism/commit/db3c7863fe3b5d1b77938ad33b7b977eda909efd

**Comment by Syer10** [comment]
Thank you for the bug report I will get to that next

**Comment by Syer10** [comment]
Fixed in af17f450c6fd6c243bc5089a190cc56172bd6177 but of course I keep messing up when I was going to reference this issue.
